; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "My Program"
#define MyAppVersion "1.5"
#define MyAppPublisher "My Company, Inc."
#define MyAppURL "https://www.example.com/"
#define MyAppExeName "MyProg.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{A66B0F36-4EF9-49C4-8537-0461C634FC71}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Uncomment the following line to run in non administrative install mode (install for current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputBaseFilename=mysetup
Compression=lzma2/fast
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Program Files (x86)\Inno Setup 6\Examples\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "E:\Users\amade\rifef\VSTRT\*"; DestDir: "{app}\VSTRT"; Flags: recursesubdirs createallsubdirs     ;Excludes: "models"
Source: "E:\Users\amade\rifef\installModels\*"; DestDir: "{app}\VSTRT\models"; Flags: recursesubdirs createallsubdirs 

[Code]
// Function to execute Python script
function ExecPythonScript(Params: String): Integer;
var
  ResultCode: Integer;
begin
  // Set the path to your Python executable
  Exec('python.exe', Params, '', SW_SHOW, ewWaitUntilTerminated, ResultCode);
  Result := ResultCode;
end;

// Example: Executing a Python script during installation
procedure CurStepChanged(CurStep: TSetupStep);
begin
  // Check if it's the post-install step
  if CurStep = ssPostInstall then
  begin
    // Execute your Python script with appropriate parameters
    ExecPythonScript('F:\all\GitHub\vs-mlrt\scripts\installerCopier.py');
  end;
end;



//; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

